# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'MLBench '
tagline:          'Distributed Machine Learning Benchmark'
description:      'A public and reproducible collection of reference implementations and benchmark suite for distributed machine learning systems. Benchmark for large scale solvers, implemented on different software frameworks & systems.'
url:              http://mlbench.github.io
baseurl:          'https://mlbench.github.io/'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mlbench/mlbench
